//ACTIONS CREATED TO FETCH MOVIE DATA
export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAILURE = 'FETCH_FAILURE';

//ADD TO A DEFAULT CATEGORY FAVORITES TV-SHOWS AT THE MOMENT
export const ADD_TO_FAVORITES = 'ADD_TO_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';

//TO SPECIFY THE CURRENT ITEM THE USER CHOOSES TO ADD TO A CATEGORY OR TO VIEW THE DETAILS
export const LOAD_CURRENT_SHOW = 'LOAD_CURRENT_SHOW';
export const ADJUST_SHOW_NUMBER = 'ADJUST_SHOW_NUMBER';
